config/routes.rb
Obipost::Application.routes.draw do
    resources :users
    resources :sessions, :only => [:new, :create, :destroy]
    resources :posts
    
    match '/signup',  :to => 'users#new'
    match '/signin',  :to => 'sessions#new'
    match '/signout', :to => 'sessions#destroy'

    match '/signup',  :to => 'users#new'
    match '/contact', :to => 'pages#contact'
    match '/about',   :to => 'pages#about'
    match '/faq',    :to => 'pages#faq'
    
    root :to => 'pages#home'
    
    
    
    
    
    
    
    
    
    
end

app/views/layouts/_footer.html.erb
<br />
<footer>
&copy; 2010 Obipost
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="round">
	  <%= link_to "Home", root_path %> | 
	  <%= link_to "FAQ", faq_path %> | 
	  <%= link_to "About", about_path %> | 
	  <%= link_to "Contact us", contact_path %>
	  &nbsp;-&nbsp;
	  <% if signed_in? %>
		<b><%= link_to "My Posts", current_user %></b> | 
		<%= link_to "Settings", edit_user_path(current_user) %> |
		<%= link_to "Signout", signout_path, :method => :delete %>
	  <% else %>
		<%= link_to "Sign in", signin_path %> |
		<%= link_to "Sign up", signup_path %>
	  <% end %>

	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'obipost', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
	<title><%= title %></title>
	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js",
							   "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.5/jquery-ui.min.js",
							   "jquery.qtip-1.0.0-rc3.min.js",
							   "rails",
							   "application" %>
</head>

<body>
<div id="wrap">
	<div id="container">
		
		<div id="header">
			<%= image_tag("obipost.png") %>
			<div id="status">
				<div id="static-links">
				<%= link_to "Home", root_path %>&nbsp;&nbsp;
				<%= link_to "FAQ", faq_path %>&nbsp;&nbsp;
				<%= link_to "About", about_path %>&nbsp;&nbsp;
				<%= link_to "Contact us", contact_path %>&nbsp;&nbsp;
				<% if signed_in? %>
					<%= current_user.email %> - 
					<%= link_to "Signout", signout_path, :method => :delete %>
				<% else %>
					<b><%= link_to "Sign in", signin_path %></b>
				<% end %>
				</div>
			</div>
		</div>
		<% if params[:controller] == "posts" %>
		<% else %>
			<div id="create-new">
				<% if signed_in? %>
					<%= button_to "Create a new flyer", new_post_path, :class => "create-new", :method => :get %>
				<% else %>
					<%= button_to "Sign up", signup_path, :class => "create-new", :method => :get %>
				<% end %>
			</div>
		<% end %>
		
		
		<% if params[:controller] == "posts" %>
			<div id="steps"><%= render "steps_progress", :post => @post %></div>
		<% else %>
			<div id="nav">
				<ul>
					<% if signed_in? %>
						<li><%= link_to "My Flyers", current_user %>
						<li><%= link_to "My Account", edit_user_path(current_user) %>
					<% end %>
				</ul>
				<br class="clear" />
			</div>
		<% end %>
		
		<div id="content">
			<div id="page">
				<% flash.each do |key, value| %>
				<div class="flash <%= key %>"><%= value %></div>
				<% end %>
				<h1><%= @title %></h1>
				<%= yield %>
			</div>
			<div class="sidebar">
				<%= yield :sidebar %>
			</div>
			<div class="clear"></div>
		</div>
		
		<div id="footer">
		</div>

	</div>
</div>

</body>
</html>

app/views/layouts/post.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
aasdasd
<%= yield %>
</body>
</html>